config/routes.rb
Rails.application.routes.draw do
  get 'about/about'
  get 'lost/lost'

  resources :posts
  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'posts', to: 'posts#new', as: 'posts'
  get 'mypost', to: 'posts#mypost', as: 'mypost'
  get '/search',to: 'posts#search', as: 'search_page'
  get 'posts/create', to: 'posts#create', as: 'create'
  get 'posts/show', to: 'posts#show', as: 'show'
  get 'posts/index', to: 'posts#index', as: 'index'
  get '/lost', to: 'posts#lost', as: 'lost'
  get '/find', to: 'posts#find', as: 'find'
   get '/found', to: 'posts#found', as: 'found'
  get '/about', to: 'about#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :cover_picture
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  helper_method :current_post
  
  def current_post
      @current_post ||= Post.all
  end

  def current_user  	
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lost_controller.rb
class LostController < ApplicationController
  def lost
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def lost
    @result = Post.where(catagory:"lost")
  end
  def find
    @result = Post.where(catagory:"find")
  end
  def found
    @result = Post.where(catagory:"found")
  end
  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mypost
  end

  def search  
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search]
      @results = Post.all.where("username LIKE :search OR title LIKE :search OR 
      content LIKE :search", search: "%#{@parameter}%")
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def post_params
      params.require(:post).permit(:username, :catagory, :title, :content, :cover_picture)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      redirect_to root_url, notice: 'Username or password is invalid!' 
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :firstname, :lastname, :phone)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lost_helper.rb
module LostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<main>
	<div class="typePost" align="center">
		<span class="dot1"></span>
		<span> LOST </span>
		<span class="dot2"></span>
		<span> FIND </span>
		<span class="dot3"></span>
		<span> FOUND </span>
	</div>
	<%= render 'posts/index'%>
</main>

app/views/layouts/_header.html.erb
<head>
  <title>Lost Find Found Cat & Dog </title>
  <link href="https://fonts.googleapis.com/css?family=Itim&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="grid-container">
    <header>
        <img style="width: 100%;" src="/images/Banner.gif" height="270px;">
        <div class="tab" style="float: right;">
            <%= link_to root_path, class:"btnTap" do %>
                <%= image_tag('/images/home-icon-silhouette.png', style:"margin-right: 10px;", height:"20", width:"20") %>HOME
            <% end %>
            <%= link_to lost_path, class:"btnTap" do %>
                <%= image_tag('/images/wanted.png', style:"margin-right: 10px;", height:"20", width:"20") %>LOST
            <% end %>
            <%= link_to find_path, class:"btnTap" do %>
                <%= image_tag('/images/find.png', style:"margin-right: 10px;", height:"20", width:"20") %>FIND
            <% end %>
            <%= link_to found_path, class:"btnTap" do %>
                <%= image_tag('/images/pawprint.png', style:"margin-right: 10px;", height:"20", width:"20") %>FOUND
            <% end %>
            <%= link_to about_path, class:"btnTap" do %>
                <%= image_tag('/images/information.png', style:"margin-right: 10px;", height:"20", width:"20") %>ABOUT
            <% end %>
        </div>
    </header>

app/views/posts/_index.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>

<div class="notice">
<p id="notice"><%= notice %></p>
</div>
<div class="field">
<%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
    <center><%= search_field_tag :search, params[:search], placeholder: "Search....", class: "search-box" %>  
      <%= button_tag "ค้นหา",class:"search-button",:name => nil%></center>  
<% end %>
</div><br>

<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>

<% current_post.reverse.each do |post| %>
 <div class="card-<%= post.catagory %>" >
    <img class ="img-post-<%= post.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(post.cover_picture) if post.cover_picture.attached? %>
    <div class="post-<%= post.catagory %>">
      <div class="edit-delete">
        <% if current_user %>
      <% if (current_user.username == post.username) or (current_user.username  == "admin")  %>
        <%= link_to image_tag('/images/edit.png'), edit_post_path(post) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), post, method: :delete, data: { confirm: 'Are you sure?' }, class:'delete' %>
      <% end %>
       <% end %>
      </div>
      <p class="post-name-<%= post.catagory %>">ชื่อโพสต์: <%= post.title %></p>
      <p class = "detail-<%= post.catagory %>" style="font-size: 16px"><%= post.content %>
      </p>
    </div>      
    <div class = "<%= post.catagory %>">
      <p>ผู้โพสต์ : <%= post.username %></p>
      <% @user_phone = User.where("username = ? ", post.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= post.created_at %></p>
      <p>แก้ไขล่าสุด : <%= post.updated_at %></p>

    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<style type="text/css">
	.form-post{
		margin: auto;
  		width: 50%;
  		padding: 10px;
	}
</style>
<main>
  <center><h1>Editing Post</h1></center>

<%= render 'form', post: @post %>

</main>

app/views/posts/find.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>
<main>
  <div class="typePost" align="center">
    <span class="dot1"></span>
    <span> LOST </span>
    <span class="dot2"></span>
    <span> FIND </span>
    <span class="dot3"></span>
    <span> FOUND </span>
  </div>
  <div class="notice">
  <p id="notice"><%= notice %></p>
  </div>

<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>
<% @result.reverse.each do |post| %>
 <div class="card-<%= post.catagory %>" >
    <img class ="img-post-<%= post.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(post.cover_picture) if post.cover_picture.attached? %>
    <div class="post-<%= post.catagory %>">
      <div class="edit-delete">
        <% if current_user %>
      <% if current_user.username == post.username %>
        <%= link_to image_tag('/images/edit.png'), edit_post_path(post) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
       <% end %>
      </div>
      <p class="post-name-<%= post.catagory %>">ชื่อโพสต์: <%= post.title %></p>
      <p class = "detail-<%= post.catagory %>" style="font-size: 16px"><%= post.content %>
      </p>
    </div>      
    <div class = "<%= post.catagory %>">
      <p>ผู้โพสต์ : <%= post.username %></p>
      <% @user_phone = User.where("username = ? ", post.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= post.created_at %></p>
      <p>แก้ไขล่าสุด : <%= post.updated_at %></p>
    </div>
  </div>
<% end %>
</main>

app/views/posts/found.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>
<main>
<div class="typePost" align="center">
    <span class="dot1"></span>
    <span> LOST </span>
    <span class="dot2"></span>
    <span> FIND </span>
    <span class="dot3"></span>
    <span> FOUND </span>
</div>
<div class="notice">
<p id="notice"><%= notice %></p>
</div>
<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>
<% @result.reverse.each do |post| %>
 <div class="card-<%= post.catagory %>" >
    <img class ="img-post-<%= post.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(post.cover_picture) if post.cover_picture.attached? %>
    <div class="post-<%= post.catagory %>">
      <div class="edit-delete">
        <% if current_user %>
      <% if current_user.username == post.username %>
        <%= link_to image_tag('/images/edit.png'), edit_post_path(post) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
       <% end %>
      </div>
      <p class="post-name-<%= post.catagory %>">ชื่อโพสต์: <%= post.title %></p>
      <p class = "detail-<%= post.catagory %>" style="font-size: 16px"><%= post.content %>
      </p>
    </div>      
    <div class = "<%= post.catagory %>">
      <p>ผู้โพสต์ : <%= post.username %></p>
      <% @user_phone = User.where("username = ? ", post.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= post.created_at %></p>
      <p>แก้ไขล่าสุด : <%= post.updated_at %></p>
      
    </div>
  </div>
<% end %>
</main>

app/views/posts/home.html.erb
<main>
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Catagory</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.catagory %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</main>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<main>
    <p id="notice"><%= notice %></p>
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Catagory</th>
      <th>Title</th>
      <th>Detail</th>
      <th>Username</th>
      <th>Catagory</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.catagory %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= image_tag post.cover_picture %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</main>

app/views/posts/lost.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>
<main>
  <div class="typePost" align="center">
    <span class="dot1"></span>
    <span> LOST </span>
    <span class="dot2"></span>
    <span> FIND </span>
    <span class="dot3"></span>
    <span> FOUND </span>
  </div>
  <div class="notice">
  <p id="notice"><%= notice %></p>
  </div>
<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>
<% @result.reverse.each do |post| %>
 <div class="card-<%= post.catagory %>" >
    <img class ="img-post-<%= post.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(post.cover_picture) if post.cover_picture.attached? %>
    <div class="post-<%= post.catagory %>">
      <div class="edit-delete">
        <% if current_user %>
      <% if current_user.username == post.username %>
        <%= link_to image_tag('/images/edit.png'), edit_post_path(post) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
       <% end %>
      </div>
      <p class="post-name-<%= post.catagory %>">ชื่อโพสต์: <%= post.title %></p>
      <p class = "detail-<%= post.catagory %>" style="font-size: 16px"><%= post.content %>
      </p>
    </div>      
    <div class = "<%= post.catagory %>">
      <p>ผู้โพสต์ : <%= post.username %></p>
      <% @user_phone = User.where("username = ? ", post.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= post.created_at %></p>
      <p>แก้ไขล่าสุด : <%= post.updated_at %></p>
    </div>
  </div>
<% end %>
</main>

app/views/posts/mypost.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>

<main>
<div class="typePost" align="center">
    <span class="dot1"></span>
    <span> LOST </span>
    <span class="dot2"></span>
    <span> FIND </span>
    <span class="dot3"></span>
    <span> FOUND </span>
</div>
<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>
<h1 align='center'>My Post</h1>
<% current_post.reverse.each do |post| %>
  <% if current_user.username == post.username %>
    <div class="card-<%= post.catagory %>" >
    <img class ="img-post-<%= post.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(post.cover_picture) if post.cover_picture.attached? %>
    <div class="post-<%= post.catagory %>">
      <div class="edit-delete">
        <%= link_to image_tag('/images/edit.png'), edit_post_path(post) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <p class="post-name-<%= post.catagory %>">ชื่อโพสต์: <%= post.title %></p>
      <p class = "detail-<%= post.catagory %>" style="font-size: 16px"><%= post.content %>
      </p>
    </div>      
    <div class = "<%= post.catagory %>">
      <p>ผู้โพสต์ : <%= post.username %></p>
      <% @user_phone = User.where("username = ? ", post.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= post.updated_at %></p>
    </div>
  </div>
  
  <% end %>
<% end %>
</main>

app/views/posts/search.html.erb
<style type="text/css">
.btn {
  border: none; /* Remove borders */
  color: white; /* Add a text color */
  padding: 14px 28px; /* Add some padding */
  cursor: pointer; /* Add a pointer cursor on mouse-over */
  text-decoration: none;
  margin-left: 50px;
  border-radius: 5px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.info {background-color: #2196F3;} /* Blue */
.info:hover {background: #0b7dda;}
.edit-delete{
  float: right;
  padding: 5px;
}
</style>

<main>
<div class="typePost" align="center">
    <span class="dot1"></span>
    <span> LOST </span>
    <span class="dot2"></span>
    <span> FIND </span>
    <span class="dot3"></span>
    <span> FOUND </span>
</div>
<h1  align="center">Search Result</h1>  
<div class= "post-btn">
  <% if current_user %>
    <%= link_to "Add New Post", new_post_path ,class:" btn info" %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>
<% @results.each do |result| %>  
    <div class="card-<%= result.catagory %>" >
    <img class ="img-post-<%= result.catagory %>"style="margin: 15px; width: 200px;" <%= image_tag(result.cover_picture) if result.cover_picture.attached? %>
    <div class="post-<%= result.catagory %>">
      <div class="edit-delete">
        <% if current_user %>
      <% if current_user.username == result.username %>
        <%= link_to image_tag('/images/edit.png'), edit_post_path(result) %>
        <%= link_to image_tag('/images/delete.png',width:"30px",height:"30px"), result, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
       <% end %>
      </div>
      <p class="post-name-<%= result.catagory %>">ชื่อโพสต์: <%= result.title %></p>
      <p class = "detail-<%= result.catagory %>" style="font-size: 16px"><%= result.content %>
      </p>
    </div>      
    <div class = "<%= result.catagory %>">
      <p>ผู้โพสต์ : <%= result.username %></p>
      <% @user_phone = User.where("username = ? ", result.username).take %>
      <p>เบอร์โทร : <%= @user_phone.phone %></p>
      <p>โพสต์เมื่อ : <%= result.updated_at %></p>
    </div>
  </div>
<% end %>
</main>

app/views/users/_show.html.erb
<style type="text/css">
  .edit-btn{
    background-color: #ffdb4d;
    border: none;
    color: black;
    padding: 5px 10px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
  .edit-btn:hover{
    background-color: #ff8b1b;
  }
  .logout-btn:hover{
    background-color: #ff0001;
  }
  .logout-btn{
    background-color: #ff8b86;
    border: none;
    color: black;
    padding: 5px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
  .mypost-btn{
    background-color: #58D68D;
    border: none;
    color: black;
    padding: 5px 22px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin-right: 25px;
    margin-top:4px;
    margin-bottom:4px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
  .mypost-btn:hover{
    background-color: #07994d;
  }
  p{
    font-size: 18px;
  }



</style>
<menu>
  <div class="login">
    <h1>- My Profile -</h1>
    <p>
      <label>Username:</label>
      <%= current_user.username %>
    </p>

    <p>
      <label>Firstname:</label>
      <%= current_user.firstname %>
    </p>

    <p>
      <label>Lastname:</label>
      <%= current_user.lastname %>
    </p>

    <p>
      <label>Phone:</label>
      <%= current_user.phone %>
    </p>
    <span>

<div style="float: left;">
    <%= button_to "Edit Profile", edit_user_path(current_user),class:"edit-btn",:method => :get %>
    </div>
    <div style="float: right;">
<%= button_to "My Post", mypost_path,class:"mypost-btn",:method => :get %>
</div>
      <center><%= button_to "Log Out", logout_path,class:"logout-btn",:method => :get %><br></center>
</span>
  </div>
</menu>